name: build and push docker images

on:
  workflow_call:
    inputs:
      app:
        type: string
        required: true
      dockerfile:
        type: string
        required: true
      working-directory:
        type: string
        required: false
        default: .
      container-registry:
        type: string
        required: false
        default: ghcr.io
      container-path:
        type: string
        required: false
        default: ${{ github.repository}}

jobs:
  docker:
    name: build and push docker image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
    - name: check out the repo
      uses: actions/checkout@v4

    - name: set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: https://${{ inputs.container-registry }}
        username: ${{ github.actor }}o
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.container-registry }}/${{ inputs.container-path}}/${{ inputs.app }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=sha
          type=raw,value=edge,enable=${{ startswith(github.ref, 'refs/heads/feature') }}
          type=raw,value=develop,enable=${{ github.ref == 'refs/heads/develop' }}
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

    - name: build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:/${{ inputs.app }}"
        file: ./${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}

