name: run validation for js

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
        default: .
      node-version:
        type: string
        required: false
        default: 22

jobs:
  lint:
    name: check lint
    runs-on: [self-hosted, node22]

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
    - name: check out the repo
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: npm install
      run: npm install

    - name: run lint
      run: npm run lint

